### ISSUE TITLE
Auto Update Not Working

### ISSUE THREAD

**Issue by Suratgit** [Nageshwar128/TataSky-Playlist-AutoUpdater#3]
I have updated my script using autoupdater package.

But i am getting error after 12 hours ...

**Comment by Nageshwar128** [comment]
More details are required, Can't magically solve the issue.

**Comment by Nageshwar128** [comment]
Nice retard move here btw:
https://github.com/Suratgit/TataSky-Playlist-AutoUpdater/commit/5dd2d98c83a504b82a2f5242be3c52f4cee955f8

Closing this issue!
